/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tablas_Interfacez;

import Herramientas.Sesion;
import Interfaz.Login;
import Paginacion.Paginacion;
import Reloj.Reloj;
import TablasDAO.AsistenciasDAO;
import TablasDAO.TurnosDAO;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Lozy
 */
public class Asistencias extends javax.swing.JFrame {

    
    AsistenciasDAO t;
    Connection con;
    String us;
    int i=0;
    int inicio=0;
    int fin=5;
    int limit;
    
    public Asistencias(Connection c, String u) {
        con = c;
        us = u;
        AsistenciasDAO tu = new AsistenciasDAO(con);
        t = tu;
        initComponents();
        Date date = new Date();
        fecha.setDate(date);
        SpinnerNumberModel nmH1 = new SpinnerNumberModel();
        SpinnerNumberModel nmH2 = new SpinnerNumberModel();
        SpinnerNumberModel nmM1 = new SpinnerNumberModel();
        SpinnerNumberModel nmM2 = new SpinnerNumberModel();
        nmH1.setMaximum(23);
        nmH1.setMinimum(0);
        nmH2.setMaximum(23);
        nmH2.setMinimum(0);
        spH1.setModel(nmH1);
        spH2.setModel(nmH2);
        nmM1.setMaximum(59);
        nmM1.setMinimum(0);
        nmM2.setMaximum(59);
        nmM2.setMinimum(0);
        spM1.setModel(nmM1);
        spM2.setModel(nmM2);
        Reloj h = new Reloj(lblReloj, u);
        h.start();
        this.setLocationRelativeTo(null);
        llenarCombos();
        tbAsistencias.setModel(t.mostrarDatos(inicio, fin));
        Paginacion p = new Paginacion(con);
        limit = getLimit(Integer.parseInt(p.count("Asistencias")), fin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarSesion = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        lblCruz = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        cbEmpleado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        Crear = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAsistencias = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbEstatus = new javax.swing.JComboBox<>();
        spM2 = new javax.swing.JSpinner();
        spH1 = new javax.swing.JSpinner();
        spM1 = new javax.swing.JSpinner();
        spH2 = new javax.swing.JSpinner();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblDia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 600));
        setMinimumSize(new java.awt.Dimension(1080, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrarSesion.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        lblReloj.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(255, 255, 255));
        lblReloj.setText("Lorem");
        getContentPane().add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblCruz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Cruz.png"))); // NOI18N
        lblCruz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCruzMouseClicked(evt);
            }
        });
        getContentPane().add(lblCruz, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        lblBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Barra.png"))); // NOI18N
        lblBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBarraMouseDragged(evt);
            }
        });
        lblBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBarraMousePressed(evt);
            }
        });
        getContentPane().add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        jLabel1.setText("Asistencias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        jLabel2.setText("Estatus:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        jLabel4.setText("Hora entrada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        jLabel5.setText("Hora salida:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        fecha.setDateFormatString("yyyy-MM-dd");
        fecha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fechaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fechaMouseExited(evt);
            }
        });
        fecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaPropertyChange(evt);
            }
        });
        fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fechaKeyReleased(evt);
            }
        });
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 210, -1));

        cbEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 180, -1));

        jLabel13.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Regresar");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 80, 30));

        Crear.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 12)); // NOI18N
        Crear.setForeground(new java.awt.Color(255, 255, 255));
        Crear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Crear.setText("Crear");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        getContentPane().add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 80, 30));

        lblEliminar.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 12)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("Eliminar");
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 80, 30));

        lblModificar.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 12)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificar.setText("Modificar");
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
        });
        getContentPane().add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 80, 30));

        jLabel7.setText(":");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 30, -1));

        jLabel8.setText(":");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 30, -1));

        tbAsistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idAsistencia", "HoraEntrada", "HoraSalida", "Dia", "Empleado"
            }
        ));
        tbAsistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAsistenciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAsistencias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 640, 220));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondoBotonAzul.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondoBotonRojo.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondoBotonRosa.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondoBotonV.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel17.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        jLabel17.setText("Empleado:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cbEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "I" }));
        getContentPane().add(cbEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 180, -1));
        getContentPane().add(spM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 60, -1));
        getContentPane().add(spH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, -1));
        getContentPane().add(spM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, -1));
        getContentPane().add(spH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 60, -1));

        btnAtras.setText("<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, -1, -1));

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        lblDia.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 12)); // NOI18N
        getContentPane().add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_lblBarraMousePressed
   
    private void lblBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_lblBarraMouseDragged

    private void lblCruzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCruzMouseClicked
        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_lblCruzMouseClicked

    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked
        Sesion s = new Sesion(con);
        if(s.cerrarSesion()){
            Login l = new Login();
            l.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesionMouseClicked

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
       
        String ca[] = cbEmpleado.getSelectedItem().toString().split("\\.");
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat dia = new SimpleDateFormat("EEEE");
        String d = dia.format(fecha.getDate());
        System.out.println(spH1.getValue()+":"+spM1.getValue()+":00");
        System.out.println(spH2.getValue()+":"+spM2.getValue()+":00");
        System.out.println(d);
        if(verificar(ca[0])){
            System.out.println(((JTextField)fecha.getDateEditor().getUiComponent()).getText());
            t.insertar(((JTextField)fecha.getDateEditor().getUiComponent()).getText(), spH1.getValue()+":"+spM1.getValue()+":00", spH2.getValue()+":"+spM2.getValue()+":00", d, ca[0], cbEstatus.getSelectedItem().toString());
            tbAsistencias.setModel(t.mostrarDatos(inicio, fin));
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Los campos han sido rellenados de forma incorrecta");
        }
        
    }//GEN-LAST:event_CrearMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        MenuTablas m = new MenuTablas(con, us);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        int fila = tbAsistencias.getSelectedRow();
        String [] op = {"Si","No"};
        String id = ""+tbAsistencias.getValueAt(fila, 0);
        if(verificar(id)){ 
            
            int b = JOptionPane.showOptionDialog(null,"¿Deseas eliminar este registro?",
                    "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, op,op[0]);
            if(b == 0){
                t.eliminar(id);
            }        
            limpiar();
            tbAsistencias.setModel(t.mostrarDatos(inicio, fin));
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun registro");
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat dia = new SimpleDateFormat("EEEE");
        String d = dia.format(fecha.getDate());
        String ca[] = cbEmpleado.getSelectedItem().toString().split("\\.");
        int fila = tbAsistencias.getSelectedRow();
        String m = (String)tbAsistencias.getValueAt(fila, 0);
        if(verificar(ca[0])){
            System.out.println(((JTextField)fecha.getDateEditor().getUiComponent()).getText());
            t.actualizar(((JTextField)fecha.getDateEditor().getUiComponent()).getText(), spH1.getValue()+":"+spM1.getValue()+":00", spH2.getValue()+":"+spM2.getValue()+":00", d, ca[0], cbEstatus.getSelectedItem().toString(),m);
            tbAsistencias.setModel(t.mostrarDatos(inicio, fin));
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Los campos han sido rellenados de forma incorrecta");
        }
    }//GEN-LAST:event_lblModificarMouseClicked

    private void tbAsistenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAsistenciasMouseClicked
        int fila = tbAsistencias.getSelectedRow();
        String r[];
        String m = (String)tbAsistencias.getValueAt(fila, 0);
        r = t.busquedaIndividual(m);
        String c1[] = r[2].split(":");
        System.out.println(c1[0]);
        spH1.setValue(Integer.parseInt(c1[0]));
        spM1.setValue(Integer.parseInt(c1[1]));
        String c2[] = r[3].split(":");
        System.out.println(c2[0]);
        spH2.setValue(Integer.parseInt(c2[0]));
        spM2.setValue(Integer.parseInt(c2[1]));
        
        for(int i = 0; i < cbEmpleado.getItemCount(); i++){
            System.out.println(cbEmpleado.getItemAt(i)+" "+r[5]);
            String ca[] = cbEmpleado.getItemAt(i).toString().split("\\.");

            if(ca[0].equals(r[5])){
                cbEmpleado.setSelectedIndex(i);
            }            
        }
        
        for(int i = 0; i < cbEstatus.getItemCount(); i++){
            System.out.println(cbEstatus.getItemAt(i)+" "+r[6]);
            if(cbEstatus.getItemAt(i).equals(r[6])){
                cbEstatus.setSelectedIndex(i);
            }            
        }
        
        
        try{
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)tbAsistencias.getValueAt(fila,1));          
            fecha.setDate(date);
        }catch(ParseException ex){
            
        }
    }//GEN-LAST:event_tbAsistenciasMouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if(inicio == 0){
            btnAtras.setEnabled(false);
        }else{
            btnSiguiente.setEnabled(true);
            inicio = inicio - 5;
            tbAsistencias.setModel(t.mostrarDatos(inicio, fin));
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if(inicio == limit*5){
           btnSiguiente.setEnabled(false);
       }else{
           btnAtras.setEnabled(true);
           inicio = inicio+5;
           tbAsistencias.setModel(t.mostrarDatos(inicio, fin));
       }   
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void fechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaMouseExited
        
    }//GEN-LAST:event_fechaMouseExited

    private void fechaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fechaAncestorAdded
        
    }//GEN-LAST:event_fechaAncestorAdded

    private void fechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaKeyReleased
        
    }//GEN-LAST:event_fechaKeyReleased

    private void fechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaPropertyChange
        
    }//GEN-LAST:event_fechaPropertyChange

    private void fechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaMouseClicked
        
    }//GEN-LAST:event_fechaMouseClicked
    int xx, xy;
    
    
    public boolean verificar(String id){
        
        ArrayList<String> l = t.verificarFecha(id);
        boolean f = true;
        for (int i = 0; i < l.size(); i++) {
            if(((JTextField)fecha.getDateEditor().getUiComponent()).getText().equals(l.get(i))){
                f = false;
            }else{
                f = true;
            }
        }
        
        if(fecha.equals(null) | vHora() == false | f == false){
            if(vHora() == false){
                JOptionPane.showMessageDialog(null, "Horario invalido");
            }
            if(f == false){
                JOptionPane.showMessageDialog(null, "El usuario no puede repetir la fecha de asistencia");
            }
            return false;
        }else{
            return true;
        }
    }
    
    public void limpiar(){
        fecha.setDate(null);
        spH1.setValue(0);
        spH2.setValue(0);
        spM1.setValue(0);
        spM1.setValue(0);
    }
    
    public boolean vHora(){
        // 12:00    8:45
        int a1 = (int) spH1.getValue();
        int a2 = (int) spM1.getValue();
        int b1 = (int) spH2.getValue();
        int b2 = (int) spM2.getValue();
        System.out.println(Math.abs(a1-b1) + " "+Math.abs(a2-b2) );
        if(Math.abs(a1-b1) < 8 | Math.abs(a1-b1) > 12){
            System.out.println("Hola");
            return false;
        }else{
            System.out.println("Adios");
            return true;
        }
    }
    
    public void llenarCombos() {
        t.combo(cbEmpleado, 1, "Empleados");
    }
    
    public int getLimit(int n, int lim){        
        limit = (int) Math.ceil(n/lim);
        System.out.println(n +" "+ limit);
        return limit;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Crear;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JComboBox<String> cbEstatus;
    private javax.swing.JLabel cerrarSesion;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblCruz;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JSpinner spH1;
    private javax.swing.JSpinner spH2;
    private javax.swing.JSpinner spM1;
    private javax.swing.JSpinner spM2;
    private javax.swing.JTable tbAsistencias;
    // End of variables declaration//GEN-END:variables
}
