/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tablas_Interfacez;

import Herramientas.Sesion;
import Interfaz.Login;
import Interfaz.Menu;
import Reloj.Reloj;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lozy
 */
public class MenuTablas extends javax.swing.JFrame {

    Connection con;
    String us;
    
    public MenuTablas(Connection c, String u) {
        initComponents();
        Reloj h = new Reloj(lblReloj, u);
        h.start();
        con = c;
        us = u;        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelMP = new javax.swing.JLabel();
        btnDocumentacionEmpleados = new javax.swing.JButton();
        btnCiudades = new javax.swing.JButton();
        btnTurnos = new javax.swing.JButton();
        btnestados = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnPuestos = new javax.swing.JButton();
        btnDeducciones = new javax.swing.JButton();
        btnAusencias = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPeriodos = new javax.swing.JButton();
        btnPercepciones = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        jLabelL1 = new javax.swing.JLabel();
        jLabelL2 = new javax.swing.JLabel();
        jLabelDepartamental = new javax.swing.JLabel();
        jLabelSalarial = new javax.swing.JLabel();
        jLabelMoney = new javax.swing.JLabel();
        jLabelT = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Humanst521 BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Regresar");
        jLabel2.setMaximumSize(new java.awt.Dimension(1080, 600));
        jLabel2.setMinimumSize(new java.awt.Dimension(1080, 600));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 140, 40));

        jLabelMP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMP.setText("MENU PRINCIPAL");
        getContentPane().add(jLabelMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        btnDocumentacionEmpleados.setText("Documentacion empleados");
        btnDocumentacionEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocumentacionEmpleadosMouseClicked(evt);
            }
        });
        getContentPane().add(btnDocumentacionEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 190, -1));

        btnCiudades.setText("Ciudades");
        btnCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 189, -1));

        btnTurnos.setText("Turnos");
        btnTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 189, -1));

        btnestados.setText("Estados");
        btnestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnestadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnestados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 189, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BotonLogin.png"))); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        btnPuestos.setText("Puestos");
        btnPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuestosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 189, -1));

        btnDeducciones.setText("Deducciones");
        btnDeducciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeduccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 189, -1));

        btnAusencias.setText("Ausencias Justificadas");
        btnAusencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAusenciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAusencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 189, -1));

        btnDepartamentos.setText("Departamentos");
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 189, -1));

        jLabel5.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cerrar Sesión");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        btnPeriodos.setText("Periodos");
        btnPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeriodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 190, -1));

        btnPercepciones.setText("Percepciones");
        btnPercepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercepcionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnPercepciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 190, -1));

        btnEmpleados.setText("Empleados");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 190, -1));

        jLabelL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Linea.png"))); // NOI18N
        getContentPane().add(jLabelL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 140, 490));

        jLabelL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Linea.png"))); // NOI18N
        getContentPane().add(jLabelL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 140, 490));

        jLabelDepartamental.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDepartamental.setText("DEPARTAMENTAL");
        getContentPane().add(jLabelDepartamental, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabelSalarial.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSalarial.setText("SALARIAL");
        getContentPane().add(jLabelSalarial, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabelMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Money.png"))); // NOI18N
        getContentPane().add(jLabelMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 190, 190));

        jLabelT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Tablas.png"))); // NOI18N
        jLabelT.setText("jLabel1");
        getContentPane().add(jLabelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 200, 180));

        lblReloj.setFont(new java.awt.Font("Humanst521 BT", 1, 14)); // NOI18N
        lblReloj.setForeground(new java.awt.Color(255, 255, 255));
        lblReloj.setText("lorem");
        getContentPane().add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MenuPanel.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FondoMenu.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadesActionPerformed
        Ciudades c = null;
        try {
            c = new Ciudades(con, us);
        } catch (SQLException ex) {
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnCiudadesActionPerformed

    private void btnTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnosActionPerformed
        Turnos t = null;
        try {
            t = new Turnos(con, us);
        } catch (SQLException ex) {
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTurnosActionPerformed

    private void btnestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnestadosActionPerformed
   Estados t = null;
        try {
            t = new Estados(con, us);
        } catch (SQLException ex) {
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnestadosActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
  
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuestosActionPerformed
        Puestos t = null;
        try{
            t = new Puestos(con, us);
        } catch(SQLException ex){
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPuestosActionPerformed

    private void btnDeduccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeduccionesActionPerformed
        Deducciones t = null;
        try{
            t = new Deducciones(con, us);
        } catch(SQLException ex ){
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeduccionesActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        Menu m = new Menu(con, us);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed
                Departamentos t = null;
        try{
            t = new Departamentos(con, us);
        } catch(SQLException ex ){
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnPercepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercepcionesActionPerformed
   Percepciones t = null;
        try {
            t = new Percepciones  (con, us);
        } catch (SQLException ex) {
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPercepcionesActionPerformed

    private void btnPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodosActionPerformed
        Periodos p = null;
        try{
            p = new Periodos(con, us);
        } catch(SQLException ex ){
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPeriodosActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        Empleados t = null;
        try{
            t = new Empleados(con, us);
        } catch(SQLException ex ){
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Sesion s = new Sesion(con);
        if(s.cerrarSesion()){
            Login l = new Login();
            l.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnDocumentacionEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentacionEmpleadosMouseClicked
        // TODO add your handling code here:
         DocumentacionEmpleado t = null;
        try {
            t = new DocumentacionEmpleado  (con, us);
        } catch (SQLException ex) {
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDocumentacionEmpleadosMouseClicked

    private void btnAusenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAusenciasActionPerformed
        AusenciasJustificadas a = null;
        try{
            a = new AusenciasJustificadas(con, us);
        } catch(SQLException ex ){
            Logger.getLogger(MenuTablas.class.getName()).log(Level.SEVERE, null, ex);
        }
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAusenciasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAusencias;
    private javax.swing.JButton btnCiudades;
    private javax.swing.JButton btnDeducciones;
    private javax.swing.JButton btnDepartamentos;
    private javax.swing.JButton btnDocumentacionEmpleados;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPercepciones;
    private javax.swing.JButton btnPeriodos;
    private javax.swing.JButton btnPuestos;
    private javax.swing.JButton btnTurnos;
    private javax.swing.JButton btnestados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDepartamental;
    private javax.swing.JLabel jLabelL1;
    private javax.swing.JLabel jLabelL2;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelMoney;
    private javax.swing.JLabel jLabelSalarial;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables
}
